import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { DiscordIcon } from "@/components/DiscordIcon";
import { ServerButton } from "@/components/ServerButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Ginto = localFont({
  variable: "--font-ginto",
  src: [
    {
      path: "../public/fonts/ginto/ginto-semibold.woff",
      weight: "600",
      style: "normal",
    },
  ],
});

const Whitney = localFont({
  variable: "--font-whitney",
  src: [
    {
      path: "../public/fonts/whitney/whitney-light.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/whitney/whitney-book.woff",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/whitney/whitney-medium.woff",
      weight: "600",
      style: "demi-bold",
    },
    {
      path: "../public/fonts/whitney/whitney-semibold.woff",
      weight: "700",
      style: "bold",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Ginto.variable} ${Whitney.variable}  antialiased`}>
        <div className="flex text-gray-100 h-screen">
          <div className="bg-gray-900 p-3 space-y-2 overflow-y-scroll scroll-thin">
            <ServerButton href={"/"} label={"Discord"}>
              <DiscordIcon className="w-7 h-5 text-gray-100" />
            </ServerButton>
            <ServerButton href={"/servers/1"} label="S1" />
            {/*{[...Array(40)].map((_, i) => (*/}
            {/*  <div*/}
            {/*    key={i}*/}
            {/*    className="bg-white text-gray-800 w-12 h-12 rounded-full flex items-center justify-center"*/}
            {/*  >*/}
            {/*    {i}*/}
            {/*  </div>*/}
            {/*))}*/}
          </div>
          {children}
        </div>
        <div />
      </body>
    </html>
  );
}